# OpenAPI version is critical to Connexion working properly.
# At time of writing, it must be 3.0.x, and only 3.0.1 is known for sure to
# work.
openapi: "3.0.1"

info:
  title: Station Data Portal API
  description: Get information from from a PCDS/CRMP database. Includes networks, variables, stations, histories.
  version: "0.1"

servers:
  - url: http://localhost:5000
    description: Local dev server
  - url: https://services.pacificclimate.org/station-data-portal
    description: Production server

tags:
  - name: Networks
    description: |
      A network groups together a set of stations and variables (see Variables).
      Typically a network is owned or managed by a single organization or entity,
      which often forms part of the network name.
  - name: Variables
    description: |
      A variable defines a physical quantity that is reported by one or more
      stations in a network. A variable is a memeber of a network and has
      zero or more observations associated with it.
  - name: Frequencies
    description: |
      A frequency is a nominal reporting interval for a history.
  - name: Histories
    description: |
      A history defines a period in the lifetime of a single station,
      giving its name, location, frequency of reporting, and variables reported,
      and specifying the period of time for which this is true.
  - name: Stations
    description: |
      A station represents a source of observations, usually but not necessarily
      an electromechanical system for measuring environmental variables.
      A station has one or more histories that define its working lifetime.
  - name: Observations
    description: |
      An observation is a single datum reported by a station for a particular
      variable.
  - name: Weather
    description: |
      Weather data is obtained from the weather views and 
      matviews that support the Weather Anomaly Viewer.

paths:
  # Networks

  /networks:
    get:
      summary: List all published networks.
      description: Get a list of short-form descriptions of all published networks.
      tags:
        - Networks
      operationId: sdpb.api.networks.collection
      parameters:
        - name: provinces
          in: query
          description: |
            Filter results by provinces. Value is a string containing
            comma-separated province codes. E.g., "BC,AB".
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NetworkList"

  /networks/{id}:
    get:
      summary: Get description of a network
      description: Get long-form description of a network
      tags:
        - Networks
      operationId: sdpb.api.networks.single
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique id of resource
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Network"
        404:
          $ref: "#/components/responses/404NotFound"

  # Variables

  /variables:
    get:
      summary: List all variables.
      description: Get a list of short-form descriptions of all variables.
      tags:
        - Variables
      operationId: sdpb.api.variables.collection
      parameters:
        - name: provinces
          in: query
          description: |
            Filter results by provinces. Value is a string containing
            comma-separated province codes. E.g., "BC,AB".
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VariableList"

  /variables/{id}:
    get:
      summary: Get description of a variable.
      description: Get long-form description of a variable.
      tags:
        - Variables
      operationId: sdpb.api.variables.single
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique id of resource
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variable"
        404:
          $ref: "#/components/responses/404NotFound"

  # Frequencies

  /frequencies:
    get:
      summary: List all frequencies valid in this database.
      description: Get a list of frequency values.
      tags:
        - Frequencies
      operationId: sdpb.api.frequencies.collection
      parameters:
        - name: provinces
          in: query
          description: |
            Filter results by provinces. Value is a string containing
            comma-separated province codes. E.g., "BC,AB".
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FrequencyList"

  # Histories

  /histories:
    get:
      summary: List all histories.
      description: Get a list of short-form descriptions of all histories.
      tags:
        - Histories
      operationId: sdpb.api.histories.collection
      parameters:
        - name: compact
          in: query
          description: Return compact representation
          schema:
            type: boolean
        - name: provinces
          in: query
          description: |
            Filter results by provinces. Value is a string containing
            comma-separated province codes. E.g., "BC,AB".
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HistoryList"

  /histories/{id}:
    get:
      summary: Get description of a history
      description: Get long-form description of a history
      tags:
        - Histories
      operationId: sdpb.api.histories.single
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Unique id of resource
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/History"
        404:
          $ref: "#/components/responses/404NotFound"

  # Stations

  /stations:
    get:
      summary: List all published stations.
      description: Get a list of short-form descriptions of all stations.
      tags:
        - Stations
      operationId: sdpb.api.stations.collection
      parameters:
        - name: provinces
          in: query
          description: |
            Filter results by provinces. Value is a string containing
            comma-separated province codes. E.g., "BC,AB".
          schema:
            type: string
        - name: compact
          in: query
          description: |
            Return compact representation of stations (and histories, 
            if included).
          schema:
            type: boolean
        - name: expand
          in: query
          description: |
            Comma-separated of response items to expand in response. 
            Presently limited to "histories".
            Default: "histories" (expand histories).
            If the value of this parameter is does not include "histories",
            the values in the "histories" property are only history id's.
            If it does, the values in the "histories" property are the 
            representation that would be obtained from 
            /histories/{id}&compact=<value> .
          schema:
            type: string
        - name: stride
          in: query
          description: Get every `stride`-th station
          schema:
            type: integer
        - name: limit
          in: query
          description: Maximum number of stations to return
          schema:
            type: integer
        - name: offset
          in: query
          description: Offset of first statoin returned
          schema:
            type: integer

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationList"

  /stations/{id}:
    get:
      summary: Get description of a station
      description: Get long-form description of a station
      tags:
        - Stations
      operationId: sdpb.api.stations.single
      parameters:
        - name: id
          in: path
          required: true
          description: Unique id of resource
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Station"
        404:
          $ref: "#/components/responses/404NotFound"

  /stations/{station_id}/variables:
    get:
      summary: Get a list of station variables
      description: Get the set of variables associated with a station
      tags:
        - Stations
        - Variables
      operationId: sdpb.api.station_variables.get_station_variables
      parameters:
        - name: station_id
          in: path
          required: true
          description: Unique id of resource
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationVariables"
        404:
          $ref: "#/components"

  /stations/{station_id}/variables/{var_id}:
    get:
      summary: Get metadata about a station variable
      description: Get metadata describing a single variables associated with a station
      tags:
        - Stations
        - Variables
      operationId: sdpb.api.station_variables.get_station_variable
      parameters:
        - name: station_id
          in: path
          required: true
          description: Station to query
          schema:
            type: integer
        - name: var_id
          in: path
          required: true
          description: Variable to query
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationVariable"
        404:
          $ref: "#/components"

  /stations/{station_id}/variables/{var_id}/observations:
    get:
      summary: Get a set of observations for a station variable
      description: Gets a span of observations
      tags:
        - Stations
        - Variables
        - Observations
      operationId: sdpb.api.station_variables.get_observations
      parameters:
        - name: station_id
          in: path
          required: true
          description: Station to query
          schema:
            type: integer
        - name: var_id
          in: path
          required: true
          description: Variable to query
          schema:
            type: string
        - name: start_date
          in: query
          description: |
            Earliest date (inclusive) of observations returned.
            Default: earliest available
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: |
            Latest date (inclusive) of observations returned.
            Default: latest available
          schema:
            type: string
            format: date
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationObservations"
        404:
          $ref: "#/components/responses/404NotFound"

  /crmp_network_geoserver:
    get:
      summary: Results from crmp_network_geoserver view.
      tags:
        - Stations
      operationId: sdpb.api.crmp_network_geoserver.collection
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StationList"

  # Observations

  /observations/counts:
    get:
      summary: Get observation counts.
      description: |
        Get approximate counts of observations available for a given date range.
        #
        Response includes counts for
        * normal observations: point-in-time or short-term statistic (e.g.,
        daily mean temperature)
        * climatologies: long-term statistics, e.g., 30-year mean of temperature
        #
        Counts are returned as a hash (dict) keyed by station id.
      tags:
        - Observations
      operationId: sdpb.api.observations.get_counts
      parameters:
        - name: provinces
          in: query
          description: |
            Filter results by provinces. Value is a string containing
            comma-separated province codes. E.g., "BC,AB".
          schema:
            type: string
        - name: start_date
          in: query
          schema:
            type: string
            format: date-time
          description: Earliest date (inclusive) of observations counted.
        - name: end_date
          in: query
          schema:
            type: string
            format: date-time
          description: Latest date (inclusive) of observations counted.
        - name: station_ids
          in: query
          schema:
            type: array
            items:
              type: integer
          explode: false
          description: Report counts for these stations only.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ObservationCounts"

  # Weather

  /weather/monthly/baseline/{variable};{month}:
    get:
      summary: Get baseline monthly weather averages.
      description: |
        Get baseline monthly weather averages for a given variable 
        and month, for all stations having such data.
      tags:
        - Weather
      operationId: sdpb.api.weather.monthly.baseline.collection
      parameters:
        - name: variable
          in: path
          required: true
          schema:
            type: string
            enum:
              - precip
              - tmin
              - tmax
        - name: month
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeatherMonthlyBaselineList"

  # TODO: Change `weather` to `ongoing` or something. This will require an
  #   update to client app (WAV).
  /weather/monthly/weather/{variable};{year}-{month}:
    get:
      summary: Get ongoing monthly weather averages.
      description: |
        Get ongoing weather averages for a given variable, year and
        month, for all stations having such data.
      tags:
        - Weather
      operationId: sdpb.api.weather.monthly.weather.collection
      parameters:
        - name: variable
          in: path
          required: true
          schema:
            type: string
            enum:
              - precip
              - tmin
              - tmax
        - name: year
          in: path
          required: true
          schema:
            type: integer
            minimum: 1850
            maximum: 2100
        - name: month
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WeatherMonthlyOngoingList"

components:
  responses:
    404NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            code: "404"
            message: Resource not found

  schemas:
    # Response schemas

    ErrorResponse:
      description: Generic error response body
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
      example:
        code: "404"
        message: Message giving details of problem

    # Networks

    Network:
      description: Full representation of a network resource.
      type: object
      properties:
        id:
          description: Unique internal id of network
          type: string
        uri:
          description: URI for this network resource
          type: string
        name:
          description: Short code/abbreviation for network
          type: string
        long_name:
          description: Full name or description of network
          type: string
        color:
          description: Colour for icons etc. representing network
          type: string
        virtual:
          description: Unknown meaning; apparently always empty
          type: string
      required:
        - id
        - uri
        - name
        - long_name
        - color
        - virtual
      example:
        color: "#FF0000"
        id: 1
        long_name: Environment Canada (Canadian Daily Climate Data 2007)
        name: EC
        publish: true
        uri: "/networks/1"
        virtual:

    NetworkList:
      description: List of networks.
      type: array
      items:
        $ref: "#/components/schemas/Network"

    # Variables

    Variable:
      description: Full representation of a variable resource.
      type: object
      properties:
        id:
          description: Unique internal id of variable
          type: string
        uri:
          description: URI for this resource
          type: string
        name:
          description: Local or colloquial name of variable within network.
          type: string
        standard_name:
          description: CF Metadata standard name for base variable. cell_method is required to fully understand the meaning of the variable. (See also short_name.)
          type: string
        cell_method:
          description: CF cell_methods (note spelling difference) describing this variable.
          type: string
        short_name:
          description: Short name or code, derived from standard_name and cell_method. This attribute also groups together distinct variables that measure the same quantity, i.e., variables that are essentially the same but which may have different values for name, standard_name, cell_method.
          type: string
        display_name:
          description: Human readable display name for variable. This attribute also groups together distinct variables that measure the same quantity, i.e., variables that are essentially the same but which may have different values for name, standard_name, cell_method.
          type: string
        unit:
          description: Unit of measure for variable values.
          type: string
        precision:
          description: Precision of values. In practice, always null.
          type: integer
        network_uri:
          description: URI of network to which this variable belongs
          type: string
        tags:
          description: |
            Tags classifying this variable (e.g., "observation", "climatology")
          type: array
          items:
            type: string
      required:
        - id
        - uri
        - name
        - standard_name
        - cell_method
        - short_name
        - display_name
        - unit
        - precision
        - network_uri
        - tags
      example:
        cell_method: "time: point"
        display_name: Surface Snow Depth (Point)
        id: 450
        name: HEIGHT_OF_SNOW
        network_uri: "/networks/2"
        precision:
        short_name: surface_snow_thickness_point
        standard_name: surface_snow_thickness
        unit: cm
        uri: "/variables/450"
        tags: ["climatology"]

    VariableList:
      description: List of variables.
      type: array
      items:
        $ref: "#/components/schemas/Variable"

    # Frequencies

    Frequency:
      description: Single frequency descriptor.
      type: string

    FrequencyList:
      description: List of frequency descriptors.
      type: array
      items:
        $ref: "#/components/schemas/Frequency"

    # Histories

    History:
      description: Full representation of a history resource.
      type: object
      properties:
        id:
          description: Unique internal id of history.
          type: string
        uri:
          description: |
            URI for this history resource.
            Note: Currently omitted because it is surprsingly slow to compute
            (using Connexion uri tool). May be made optional with query param
            in future.
          type: string
        station_name:
          description: Name of station during this history.
          type: string
        lon:
          description: Longitude of station.
          type: number
        lat:
          description: Latitude of station.
          type: number
        elevation:
          description: Elevation of station.
          type: number
        sdate:
          description: |
            Start datetime of history. This value is not reliably maintained.
          type: string
          format: date-time
        edate:
          description: |
            End datetime of history. Null if it is the current history and
            this is considered an 'active' station.
            This value is not reliably maintained.
          type: string
          format: date-time
        min_obs_time:
          description: |
            Time of earliest observation associated with this history.
            Unlike `sdate`, this value is reliable and up to date.
          format: date-time
        max_obs_time:
          description: |
            Time of latest observation associated with this history.
            Unlike `edate`, this value is reliable and up to date.
          format: date-time
        tz_offset:
          description: Time zone offset. Always null in practice.
          type: string
          format: interval
        province:
          description: Code for province where station is located.
          type: string
        country:
          description: Code for country where station is located.
          type: string
        freq:
          description: Frequency of reporting.
          type: string
        variable_uris:
          description: List of URIs of variables reported.
          type: array
          items:
            type: string
      required:
        - id
        - uri
        - station_name
        - lon
        - lat
        - elevation
        - sdate
        - edate
        - max_obs_time
        - min_obs_time
        - tz_offset
        - province
        - country
        - freq
        - variable_uris
      example:
        country:
        edate:
        elevation: 13
        freq: daily
        id: 999
        lat: 54.05
        lon: -128.683333
        max_obs_time: "1996-11-30T00:00:00"
        min_obs_time: "1984-07-01T00:00:00"
        province: BC
        sdate:
        station_name: KITIMAT
        tz_offset:
        uri: "/histories/999"
        variable_uris:
          - "/variables/427"
          - "/variables/428"
          - "/variables/429"
          - "/variables/430"
          - "/variables/431"
          - "/variables/432"
          - "/variables/556"
          - "/variables/557"
          - "/variables/558"
          - "/variables/559"

    HistoryList:
      description: List of histories.
      type: array
      items:
        $ref: "#/components/schemas/History"

    # Stations

    Station:
      description: Full representation of a station resource.
      type: object
      properties:
        id:
          description: Unique internal id of station
          type: string
        uri:
          description: URI for this station resource
          type: string
        native_id:
          description: Network's identifier for station. Not necessarily unique, even within networks.
          type: string
        min_obs_time:
          description: Earliest time of observation from this station.
          type: string
          format: date-time
        max_obs_time:
          description: Latest time of observation from this station. Null value means station is still reporting.
          type: string
          format: date-time
          nullable: true
        network_uri:
          description: URI of network to which this station belongs
          type: string
        histories:
          description: History records for this station.
          type: array
          items:
            $ref: "#/components/schemas/History"
      required:
        - id
        - uri
        - native_id
        - min_obs_time
        - max_obs_time
        - network_uri
        - histories
      example:
        histories:
          - country:
            edate:
            elevation: 4
            freq: daily
            id: 404
            lat: 48.866667
            lon: -123.283333
            province: BC
            sdate:
            station_name: ACTIVE PASS
            tz_offset:
            uri: "/histories/404"
            variable_uris:
              - "/variables/429"
              - "/variables/430"
              - "/variables/431"
              - "/variables/432"
              - "/variables/559"
        id: 1
        max_obs_time: "1996-11-30T00:00:00"
        min_obs_time: "1984-07-01T00:00:00"
        native_id: "1010066"
        network_uri: "/networks/1"
        uri: "/stations/1"

    StationList:
      description: List of stations.
      type: array
      items:
        $ref: "#/components/schemas/Station"

    StationVariable:
      description: list of variables available to this station
      type: object
      allOf:
        # extend standard variable output with min and max obs times for this station
        # these are aggregate properties of both station and variable so I'm not 100% 
        # sure that this is the correct location for them to live.
        - $ref: "#/components/schemas/Variable"
        - type: object
          properties:
            min_obs_time:
              description: Earliest time of observation for this variable
              type: string
              format: date-time
            max_obs_time:
              description: Latest time of observation for this variable
              type: string
              format: date-time
            station_id:
              description: Unique internal id of station
              type: string
      required:
        - min_obs_time
        - max_obs_time
      example:
        # standard variable
        cell_method: "time: point"
        display_name: Surface Snow Depth (Point)
        id: 450
        name: HEIGHT_OF_SNOW
        network_uri: "/networks/2"
        precision:
        short_name: surface_snow_thickness_point
        standard_name: surface_snow_thickness
        unit: cm
        uri: "/variables/450"
        tags: ["climatology"]
        # station specific
        max_obs_time: "1996-11-30T00:00:00"
        min_obs_time: "1984-07-01T00:00:00"
        station_id: 1

    StationVariables:
      description: List of variables associated with a station
      type: object
      properties:
        station_id:
          description: Unique internal id of station
          type: string
        variables:
          description: list of variables available to this station
          type: array
          items:
            $ref: "#/components/schemas/StationVariable"
      required:
        - station_id
        - variables
      example:
        station_id: 1
        variables:
          - cell_method: "time: point"
            display_name: Surface Snow Depth (Point)
            id: 450
            name: HEIGHT_OF_SNOW
            network_uri: "/networks/2"
            precision:
            short_name: surface_snow_thickness_point
            standard_name: surface_snow_thickness
            unit: cm
            uri: "/variables/450"
            tags: ["climatology"]
            station_id: 1
            min_obs_time: "1984-07-01T00:00:00"
            max_obs_time: "1996-11-30T00:00:00"
          - cell_method: "time: minimum"
            display_name: Temperature (Min)
            id: 451
            name: HEIGHT_OF_SNOW
            network_uri: "/networks/2"
            precision:
            short_name: surface_snow_thickness_point
            standard_name: surface_snow_thickness
            unit: cm
            uri: "/variables/451"
            tags: ["observation"]
            station_id: 1
            min_obs_time: "1984-07-01T00:00:00"
            max_obs_time: "1996-11-30T00:00:00"


    StationObservations:
      description: List of Observations from a station's variable and its associated metadata
      type: object
      properties:
        station_id:
          type: string
          description: the requested station
        variable_id:
          type: string
          description: the requested variable
        start_date:
          type: string
          format: date-time
          description: the start date of the requested observation range
        end_date:
          type: string
          format: date-time
          description: the end date of the requested observation range
        observations:
          type: array
          items:
            type: object
            properties:
              time:
                type: string
                format: date-time
                description: the time of the observation
              value:
                type: number
                description: the value of the observation

    # Observations
    ObservationCounts:
      description: Counts of observations and climatologies, by station, in a specified date range.
      type: object
      properties:
        provinces:
          description: |
            Province filter; comma-separated province codes; e.g., "BC,AB".
          type: string
        start_date:
          description: Earliest date (inclusive) of observations counted.
          type: string
          format: date-time
        end_date:
          description: Latest date (inclusive) of observations counted.
          type: string
          format: date-time
        station_ids:
          description: Counts for these stations only.
          type: array
          items:
            type: integer
        uri:
          description: URI of this resource
          type: string
        observationCounts:
          description: Counts, by station id, of observations available in specified date range.
          type: object
        climatologyCounts:
          description: Counts, by station id, of climatologies available in specified date range.
          type: object
      required:
        - start_date
        - end_date
        - station_ids
        - uri
        - observationCounts
        - climatologyCounts
      example:
        end_date:
        start_date:
        station_ids: [1, 2, 3, 4, 5]
        uri: "/observations/counts?station_ids=1&station_ids=2&station_ids=3&station_ids=4&station_ids=5"
        climatologyCounts:
          "1": 12
          "3": 12
          "4": 12
        observationCounts:
          "1": 15857
          "2": 62488
          "3": 13544
          "4": 8040
          "5": 9330

    # Weather
    # Note these are legacy endpoints which do not conform to the pattern of
    # the other endpoints in this API. To be updated.

    WeatherMonthlyBaseline:
      description: |
        Representation of a weather monthly baseline resource for a single 
        station.
      type: object
      properties:
        network_name:
          description: Name of network station is member of.
          type: string
        station_db_id:
          description: Unique internal id of station.
          type: string
        station_native_id:
          description: Native ID. Unique identifier of station within network.
          type: string
        history_db_id:
          description: |
            Unique internal id of (station) history record
            associated with this data.
          type: string
        station_name:
          description: Station name in this history
          type: string
        lon:
          description: Longitude of station in this history.
          type: number
        lat:
          description: Latitude of station in this history.
          type: number
        elevation:
          description: Elevation of station in this history.
          type: number
        datum:
          description: Baseline value for variable within this history.
          type: number
      required:
        - network_name
        - station_db_id
        - station_native_id
        - history_db_id
        - station_name
        - lon
        - lat
        - elevation
        - datum

    WeatherMonthlyBaselineList:
      description: List of monthly weather baseline items.
      type: array
      items:
        $ref: "#/components/schemas/WeatherMonthlyBaseline"

    WeatherMonthlyOngoing:
      description: |
        Representation of a monthly weather "ongoing" resource for a single 
        station.
      type: object
      properties:
        network_name:
          description: Name of network station is member of.
          type: string
        station_db_id:
          description: Unique internal id of station.
          type: string
        station_native_id:
          description: Native ID. Unique identifier of station within network.
          type: string
        history_db_id:
          description: |
            Unique internal id of (station) history record
            associated with this data.
          type: string
        station_name:
          description: Station name in this history
          type: string
        lon:
          description: Longitude of station in this history.
          type: number
        lat:
          description: Latitude of station in this history.
          type: number
        elevation:
          description: Elevation of station in this history.
          type: number
        network_variable_name:
          description: |
            Network variable name processed for this monthly average statistic.
          type: string
        cell_method:
          description: |
            Cell methods for this variable (prior to forming monthly average).
          type: string
        frequency:
          description: Frequency of variable reporting in this history.
          type: string
        statistic:
          description: Value of monthly average statistic.
          type: number
        data_coverage:
          description: |
            Coverage of data within month contributing to this statistic value.
          type: number
          minimum: 0
          maximum: 1

    WeatherMonthlyOngoingList:
      description: List of weather ongoing items.
      type: array
      items:
        $ref: "#/components/schemas/WeatherMonthlyOngoing"
